name: Tests
on: [ push ]
jobs:
  cypress:
    name: Cypress
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [ chrome, firefox ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: current
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn run build
      - name: Run cypress tests
        uses: cypress-io/github-action@v4
        with: 
          browser: "${{ matrix.browser }}"
      - name: Upload cypress screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Upload cypress videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
